[phases.setup]
nixPkgs = ["nodejs_20", "python3", "gcc", "gnumake"]

[phases.install]
cmds = ["npm ci", "npm rebuild better-sqlite3", "npm rebuild sharp"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
